version: '3.1'

services:

  db-mysql:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 4306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
